version: '3.8'

services:
  metalmq:
    image: metalmq:0.0.1
    networks:
      - local

  amqp-test:
    build:
      context: .
      dockerfile: Dockerfile.pytest
    depends_on:
      - metalmq
    networks:
      - local

networks:
  local:
    driver: bridge
